# Generated by Django 5.2.10 on 2026-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor'), ('Event Management', 'Event Management'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
    ]
