# Generated by Django 5.2.10 on 2026-03-02 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Corporate', 'Corporate'), ('Festival', 'Festival'), ('Other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('event_location', models.CharField(max_length=255)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bookings', to='vendor.vendorprofile')),
            ],
        ),
    ]
